### ISSUE TITLE
Character Encoding issues

### ISSUE THREAD

**Issue by adamschoenemann** [duncansmart/coffeescript-windows#2]
Apparently, the windows FileSystemObject only writes text files as UCS-2 little endian encoded, which does not allow for certain special utf-8 characters. I edited the convert function to use the ADODB.Stream object instead, which allows encodings to be specified. Bear in mind that I did this very quickly, and did not test it very thoroughly, but it appears to be working.

Updated coffee.wsf can be found here: https://www.dropbox.com/s/elb90figytm9sr1/coffee.wsf

**Comment by duncansmart** [comment]
Thanks @adamschoenemann adapted a bit and committed as 93b6e7abd39d7b0c38147b4c0b51ebc1fd4152ef
